### 5.1 기본 배열 처리 함수


In [4]:
# 5.1.1 행렬 처리 함수 (뒤집기, 복사 전치)
import cv2
import numpy as np

image = cv2.imread("images_05/flip_test.jpg", cv2.IMREAD_COLOR)
if image is None: raise Exception("영상파일 읽기 오류")

# cv2.filp(배열, 방향)
x_axis = cv2.flip(image, 0) # 상하 뒤집기 (=x축 기준)
y_axis = cv2.flip(image, 1) # 좌우 뒤집기 (=y축 기준)
xy_axis = cv2.flip(image, -1) # 상화좌우 모두 뒤집기
# cv2.repeat(배열, 방향, 반복_횟수)
rep_axis = cv2.repeat(image, 1, 2) # 반복 복사
# cv2.transpose(배열)
trans_axis = cv2.transpose(image) # 행렬 전치

titles = ['image', 'x_axis', 'y_axis', 'xy_axis', 'rep_axis', 'trans_axis']

for title in titles:
    cv2.imshow(title, eval(title))
cv2.waitKey(0)

-1

### 5.2 채널 처리 함수

In [8]:
# 5.2.1 채널 분리 및 합성
import numpy as np
import cv2

# 행렬 생성 및 초기화
ch0 = np.zeros((2,4), np.uint8) + 10 # 0로 가득찬 배열 생성 후 모든 요소에 10 더하기
ch1 = np.ones((2,4), np.uint8) * 20 # 1로 가득찬 배열 생성 후 모든 요소에 20 곱하기
ch2 = np.full((2,4), 30, np.uint8) # 30으로 가득찬 배열 생성

list_bgr = [ch0, ch1, ch2] # 리스트 구성
merge_bgr = cv2.merge(list_bgr) # 채널 합성
split_bgr = cv2.split(merge_bgr) # 채널 분리 (컬러영상 -> 3개의 채널로 분리)

print("split_bgr 행렬 형태", np.array(split_bgr).shape)
print("merge_bar 행렬 형태", np.array(merge_bgr).shape)

print("[ch0] = \n%s" % ch0)
print("[ch1] = \n%s" % ch1)
print("[ch2] = \n%s" % ch2)
print("[merge_bgr] = \n%s\n" % merge_bgr)

print("[split_bgr[0]] = \n%s\n" % split_bgr[0])
print("[split_bgr[1]] = \n%s\n" % split_bgr[1])
print("[split_bgr[2]] = \n%s\n" % split_bgr[2])


split_bgr 행렬 형태 (3, 2, 4)
merge_bar 행렬 형태 (2, 4, 3)
[ch0] = 
[[10 10 10 10]
 [10 10 10 10]]
[ch1] = 
[[20 20 20 20]
 [20 20 20 20]]
[ch2] = 
[[30 30 30 30]
 [30 30 30 30]]
[merge_bgr] = 
[[[10 20 30]
  [10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]
  [10 20 30]]]

[split_bgr[0]] = 
[[10 10 10 10]
 [10 10 10 10]]

[split_bgr[1]] = 
[[20 20 20 20]
 [20 20 20 20]]

[split_bgr[2]] = 
[[30 30 30 30]
 [30 30 30 30]]



In [9]:
# 5.2.2 컬러 채널 분리
import cv2
import numpy as np

image = cv2.imread("images_05/color.jpg", cv2.IMREAD_COLOR)
if image is None: raise Exception("영상파일 읽기 오류")
if image.ndim != 3: raise Exception("컬러 영상 아님")

bgr = cv2.split(image) # 채널 분리
print("bgr 자료형:", type(bgr), type(bgr[0]), type(bgr[0][0][0]), bgr[0].shape)
print("bgr 원소개수:", len(bgr))


cv2.imshow("image", image)
cv2.imshow("Blue channel", bgr[0])
cv2.imshow("Green channel", bgr[1])
cv2.imshow("Red channel", bgr[2])
cv2.waitKey(0)

bgr 자료형: <class 'tuple'> <class 'numpy.ndarray'> <class 'numpy.uint8'> (360, 480)
bgr 원소개수: 3


-1

-> 각 채널의 색상을 가지는 요소가 밝게 표시됨 (bgr[0]에서 파란색 물체가 밝게 표시)



### 심화 : grb 중 원하는 색상만 보이게 하기

앞서 작성한 코드의 경우 grb를 따로 추출은 하였으나 출력 시 해당 색상이 밝게 보일 뿐 큰 차이를 알기 어려움 (명암으로만 물체의 색상을 확인 가능)

따라서 3채널로 만들고, 보여주고자 하는 채널을 제외한 나머지 채널을 0으로 만들어 출력한다면 색상이 보일 것임

In [9]:
# 테스트 : grb중 원하는 색상만 보이게 하기
import copy
import cv2
import numpy as np

image = cv2.imread("images_05/color.jpg", cv2.IMREAD_COLOR)
if image is None: raise Exception("영상파일 읽기 오류")
if image.ndim != 3: raise Exception("컬러 영상 아님")

# 이미지[:,:,가져올 채널] -> 행, 열은 모두 가져오고 채널(높이)만 원하는 위치의 값을 가져옴 
# 채널 분리했을 떄와 동일한 효과 (행, 열) 가져옴
b = copy.deepcopy(image)
b[:,:,1] = 0
b[:,:,2] = 0

g = copy.deepcopy(image)
g[:,:,0] = 0
g[:,:,2] = 0

r = copy.deepcopy(image)
r[:,:,0] = 0
r[:,:,1] = 0

cv2.imshow("Original", image)
cv2.imshow("Only Blue", b)
cv2.imshow("Only Green", g)
cv2.imshow("Only Red", r)
cv2.waitKey(0)





-1