### 5.3 산술 연산 함수

##### 5.3.1 사칙연산
mask : 부분 정보에만 결과를 적용시킬 때 사용함
- 배열 slising을 통해 연산을 적용할 부분 정보를 저장할 수 있음

스칼라 : 방향을 가지지 않고 크기만 갖는 물리량

In [1]:
# 5.3.1 행렬 산술 연산
import numpy as np
import cv2

m1 = np.full((3,6), 10, np.uint8)
m2 = np.full((3,6), 50, np.uint8)

m_mask = np.zeros(m1.shape, np.uint8)
m_mask[ : , 3:] = 1 # 행 전체, 열은 3이상의 모든 요소를 지정

m_add1 = cv2.add(m1, m2) 
m_add2 = cv2.add(m1, m2, mask=m_mask) # mask를 사용하여 특정 부분만 적용

titles = ['m1', 'm2', 'm_mask', 'm_add1', 'm_add2']

for title in titles:
    print("[%s] = \n%s \n" % (title, eval(title))) 



[m1] = 
[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[m2] = 
[[50 50 50 50 50 50]
 [50 50 50 50 50 50]
 [50 50 50 50 50 50]] 

[m_mask] = 
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]] 

[m_add1] = 
[[60 60 60 60 60 60]
 [60 60 60 60 60 60]
 [60 60 60 60 60 60]] 

[m_add2] = 
[[ 0  0  0 60 60 60]
 [ 0  0  0 60 60 60]
 [ 0  0  0 60 60 60]] 



In [4]:
# 5.3.2 행렬 지수 및 로그 연산
import numpy as np
import cv2

v1 = np.array([1,2,3], np.float32) # 1차원 리스트 행렬
v2 = np.array([[1],[2],[3]], np.float32) # 2차원 리스트 - 열벡터
v3 = np.array([[1,2,3]], np.float32) # 2차원 리스트 - 행벡터

# cv2.exp(배열) # 지수 계산
# cv2.log(배열) # 로그 계산
# cv2.sqrt(배열) # 제곱근 계산
# cv2.pow(배열, 값) # 거듭제곱 계산
v1_exp = cv2.exp(v1) # 1차원 행렬의 지수
v2_exp = cv2.exp(v2) # 행벡터에 대한 지수 계산
v3_exp = cv2.exp(v3) # 열벡터에 대한 지수 계산
log = cv2.log(v1) # 로그 계산
sqrt = cv2.sqrt(v2) # 제곱근 계산
pow = cv2.pow(v3, 3) # 거듭제곱 계산

# 행렬 형태 출력
print("[v1] 형태: %s 원소: %s" % (v1.shape, v1))
print("[v2] 형태: %s 원소: %s" % (v2.shape, v2))
print("[v3] 형태: %s 원소: %s" % (v3.shape, v3))
print()

print("[v1_exp] 자료형: %s 형태: %s" % (type(v1_exp), v1_exp.shape))
print("[v2_exp] 자료형: %s 형태: %s" % (type(v2_exp), v2_exp.shape))
print("[v3_exp] 자료형: %s 형태: %s" % (type(v3_exp), v3_exp.shape))
print()

# 열 벡터 -> 행 벡터로 변환
# 배열.T
# np.ravel(배열)
# 배열.flatten()
print("[log] = ", log.T) # 열벡터를 전치하여 행벡터로 변경
print("[log] = ", np.ravel(sqrt)) # 전개하여 1차원 행렬로 변경
print("[log] = ", pow.flatten()) # 전개하여 1차원 행렬로 변경


[v1] 형태: (3,) 원소: [1. 2. 3.]
[v2] 형태: (3, 1) 원소: [[1.]
 [2.]
 [3.]]
[v3] 형태: (1, 3) 원소: [[1. 2. 3.]]

[v1_exp] 자료형: <class 'numpy.ndarray'> 형태: (3, 1)
[v2_exp] 자료형: <class 'numpy.ndarray'> 형태: (3, 1)
[v3_exp] 자료형: <class 'numpy.ndarray'> 형태: (1, 3)

[log] =  [[0.        0.6931472 1.0986123]]
[log] =  [1.        1.4142135 1.7320508]
[log] =  [ 1.  8. 27.]


In [6]:
# 5.3.3 행렬 크기 및 위상 연산
import numpy as np
import cv2

x = np.array([1,2,3,5,10], np.float32)
y = np.array([2,5,7,2,9]).astype("float32") # 생성 후 실수형 변환

mag = cv2.magnitude(x, y) # 크기 계산
ang = cv2.phase(x, y) # 각도(방향) 계산
p_mag, p_ang = cv2.cartToPolar(x, y) # 극 좌표로 변환
x2, y2 = cv2.polarToCart(p_mag, p_ang) # 직교좌표로 변환

print("[x] 형태: %s 원소: %s" % (x.shape, x))
print("[mag] 형태: %s 원소: %s" % (mag.shape, mag))

[x] 형태: (5,) 원소: [ 1.  2.  3.  5. 10.]
[mag] 형태: (5, 1) 원소: [[ 2.236068 ]
 [ 5.3851647]
 [ 7.615773 ]
 [ 5.3851647]
 [13.453624 ]]


##### 5.3.3 논리(비트) 단위 연산
원소의 비트 단위로 논리 연산을 수행함

In [19]:
# 5.3.4 행렬 비트 연산
import numpy as np
import cv2

image1 = np.zeros((300,300), np.uint8) # 검정색 영상 생성
image2 = image1.copy() # 복사

h, w = image1.shape[:2] # 행, 열 정보를 저장
cx, cy = w//2, h//2 # 중심 좌표
cv2.circle(image1, (cx, cy), 100, 255, -1) # 중심에 원 그리기
cv2.rectangle(image2, (0, 0, cx, h), 255, -1) # 영상의 가로 절반

# cv2.bitwise_연산() # and/or/not/xor 연산을 수행한다.
image3 = cv2.bitwise_or(image1, image2) # 논리합
image4 = cv2.bitwise_and(image1, image2) # 논리곱
image5 = cv2.bitwise_xor(image1, image2) # 베타적 논리합
image6 = cv2.bitwise_not(image1) # 행렬 반전

cv2.imshow("image1", image1)
cv2.imshow("image2", image2)
cv2.imshow("bitwise_or", image3)
cv2.imshow("bitwise_and", image4)
cv2.imshow("bitwise_xor", image5)
cv2.imshow("bitwise_not", image6)
cv2.waitKey(0)


-1

In [5]:
# 5.3.4 행렬 비트 연산2
import numpy as np
import cv2

image = cv2.imread("images_05/bit_test.jpg", cv2.IMREAD_COLOR) # 원본 영상 읽기
logo = cv2.imread("images_05/logo.jpg", cv2.IMREAD_COLOR) # 로고 영상 읽기
if image is None or logo is None: raise Exception("영상파일 읽기 오류")

# cv2.threshold(이미지, 0_최대_범위, 1_최대_범위, cv2.THRESH_BINARY) # 0최대 범위보다 작으면 0, 큰 화소는 1
masks = cv2.threshold(logo, 220, 255, cv2.THRESH_BINARY)[1] # 컬러 채널이기 때문에 채널별로 3개로 분리되어 나옴
print("masks.shape : ", masks.shape)
masks = cv2.split(masks)

fg_pass_mask = cv2.bitwise_or(masks[0], masks[1]) 
fg_pass_mask = cv2.bitwise_or(masks[2], fg_pass_mask) # 단일 채널 3개를 합쳐서 fg_pass_mask에 저장
bg_pass_mask = cv2.bitwise_not(fg_pass_mask) # 배경 통과 마스크

(H, W), (h, w) = image.shape[:2], logo.shape[:2] # 영상들의 크기를 저장
x, y = (W-w)//2, (H-h)//2 # 시작 좌표
roi = image[y:y+h, x:x+w] # 관심 영역

foreground = cv2.bitwise_and(logo, logo, mask=fg_pass_mask) # 로고 전경만 복사
background = cv2.bitwise_and(roi, roi, mask=bg_pass_mask) # 로고 전경만 복사

dst = cv2.add(background, foreground) # 합성
image[y:y+h, x:x+w] = dst # 합성 영상을 원본에 복사

cv2.imshow('background', background)
cv2.imshow('foreground', foreground)
cv2.imshow('dst', dst)
cv2.imshow('image', image)
cv2.waitKey(0)



masks.shape :  (308, 250, 3)


-1