### 5.4 원소의 절대값 연산

In [2]:
# 5.4.1 행렬 절대값 및 차분 연산
import numpy as np
import cv2

image1 = cv2.imread("images_05/abs_test1.jpg", cv2.IMREAD_GRAYSCALE) # 명암도 영상 읽기
image2 = cv2.imread("images_05/abs_test2.jpg", cv2.IMREAD_GRAYSCALE)
if image1 is None or image2 is None: raise Exception("영상파일 읽기 오류")

dif_img1 = cv2.subtract(image1, image2) # 차분 연산 : 함수 값들의 차이
dif_img2 = cv2.subtract(np.int16(image1), np.int16(image2)) # 음수 결과 보존
abs_dif1 = np.absolute(dif_img2).astype('uint8')
abs_dif2 = cv2.absdiff(image1, image2) # 차분 절대값 계산

x, y, w, h = 100, 150, 7, 3
print("[dif_img1(roi) uint8] = \n%s\n " % dif_img1[y:y+h, x:x+w] )
print("[dif_img2(roi) uint16] = \n%s\n " % dif_img2[y:y+h, x:x+w] )
print("[abs_dif1(roi)] = \n%s\n " % abs_dif1[y:y+h, x:x+w] )
print("[abs_dif2(roi)] = \n%s\n " % abs_dif2[y:y+h, x:x+w] )

titles = ['image1', 'image2', 'dif_img1', 'abs_dif1', 'abs_dif2']
for title in titles:
    cv2.imshow(title, eval(title))
cv2.waitKey(0)

[[165 169 171 ... 102 102 102]
 [165 169 171 ...  99 102 104]
 [165 169 171 ...  98 107 109]
 ...
 [ 72  50  59 ...  78  75  74]
 [ 59  55  60 ...  77  74  70]
 [ 54  77  56 ...  70  75  75]]
[dif_img1(roi) uint8] = 
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
 
[dif_img2(roi) uint16] = 
[[-185 -195 -192 -193 -201 -176 -133]
 [-193 -196 -190 -194 -198 -182 -122]
 [-194 -193 -190 -187 -178 -199 -155]]
 
[abs_dif1(roi)] = 
[[185 195 192 193 201 176 133]
 [193 196 190 194 198 182 122]
 [194 193 190 187 178 199 155]]
 
[abs_dif2(roi)] = 
[[185 195 192 193 201 176 133]
 [193 196 190 194 198 182 122]
 [194 193 190 187 178 199 155]]
 


-1

In [6]:
# 5.4.2 행렬 최대값 및 최소값 연산
import numpy as np
import cv2

data = [10, 200, 5, 7, 9, 15, 35, 60, 80, 170, 100, 2, 55, 37, 70]
m1 = np.reshape(data, (3,5))
m2 = np.full(m1.shape, 50)

m_min = cv2.min(m1, 30) # m1의 요소 중 30보다 작은 값은 유지, 30보다 큰 값은 30
m_max = cv2.max(m1, m2) # m1, m2의 요소 중 큰 값을 가짐

min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(m1) # 행렬의 최소값, 최대값, 좌표위치를 받아옴

print("[m1] = \n%s\n" % m1)
print("[m_min] = \n%s\n" % m_min)
print("[m_max] = \n%s\n" % m_max)

print("m1 행렬 최소값 좌표: %s, 최소값: %d" %(min_loc, min_val)) # 좌표가 헷갈릴 수 있음, 잘 확인해야 함
print("m1 행렬 최대값 좌표: %s, 최대값: %d" %(max_loc, max_val))

[m1] = 
[[ 10 200   5   7   9]
 [ 15  35  60  80 170]
 [100   2  55  37  70]]

[m_min] = 
[[10 30  5  7  9]
 [15 30 30 30 30]
 [30  2 30 30 30]]

[m_max] = 
[[ 50 200  50  50  50]
 [ 50  50  60  80 170]
 [100  50  55  50  70]]

m1 행렬 최소값 좌표: (1, 2), 최소값: 2
m1 행렬 최대값 좌표: (1, 0), 최대값: 200


In [7]:
# 5.4.3 영상 최소값 최대값 연산
import numpy as np
import cv2

image = cv2.imread("images_05/minMax.jpg", cv2.IMREAD_GRAYSCALE) # 명암도 영상 읽기
if image is None: raise Exception("영상파일 읽기 오류")

min_val, max_val, _, _ = cv2.minMaxLoc(image) # 최소값, 최대값 불러오기
ratio = 255 / (max_val - min_val) # 차분으로 나누어 비율 계산
dst = np.round((image - min_val) * ratio).astype('uint8') # 최소 값으로 뺀 후 비율을 곱하여 영상 내 최소값이 0, 최대 값이 255가 되도록 함
min_dst, max_dst, _, _ = cv2.minMaxLoc(dst)

print("원본 영상 최소값: %d, 최대값: %d" %(min_val, max_val))
print("수정 영상 최소값: %d, 최대값: %d" %(min_dst, max_dst))
cv2.imshow('image', image)
cv2.imshow('dst', dst)
cv2.waitKey(0)


원본 영상 최소값: 13, 최대값: 107
수정 영상 최소값: 0, 최대값: 255


-1

-> 최대 최소값을 0과 255로 만들었기 때문에 어두운 부분은 더 어둡게, 밝은 부분은 더 밝게 보임

--------
순서

1. 최소값이 0이 되도록 한다. 

2. 최소값이 0이 되도록하는 값으로 모든 데이터의 값을 뺀다. (차분)

3. 모든 데이터의 값을 최대값이 255로 되도록 만드는 값을 곱한다 (= Ratio)


얼마나 끌어 당겨서 최대값을 255로 만들 수 있는가? : Ratio = 255/(Max-Min)

### 5.5 통계 관련 함수

In [11]:
# 5.5.1 행렬 합/평균 연산
import numpy as np
import cv2

image = cv2.imread("images_05/sum_test.jpg", cv2.IMREAD_COLOR) 
if image is None: raise Exception("영상파일 읽기 오류")

mask = np.zeros(image.shape[:2], np.uint8) # 관심(마스크) 영역
mask[60:160, 20:120] = 255 # 관심영역에 값 할당 # 행(세로 60~160)이 먼저, 다음이 열(가로 20~120)임

sum_value = cv2.sumElems(image) # 채널별 합
mean_value1 = cv2.mean(image) # 채널별 평균
mean_value2 = cv2.mean(image, mask) # 마스크 원소에 해당하는 부분만 평균을 계산함

print("sum_value 자료형: ", type(sum_value), type(sum_value[0]))
print("[sum_value] = ", sum_value)
print("[mean_value1] = ", mean_value1)
print("[mean_value2] = ", mean_value2)
print()

mean, stddev = cv2.meanStdDev(image) # 평균, 표준편차
mean2, stddev2 = cv2.meanStdDev(image, mask=mask) # 마스크 영역 부분만 계산
print("mean 자료형: ", type(mean), type(mean[0][0]))
print("[mean] = ", mean.flatten())
print("[stddev] = ", stddev.flatten())
print()
print("[mean2] = ", mean2.flatten())
print("[stddev2] = ", stddev2.flatten())

cv2.imshow('image', image)
cv2.imshow('mask', mask)
cv2.waitKey(0)

sum_value 자료형:  <class 'tuple'> <class 'float'>
[sum_value] =  (15865577.0, 15880547.0, 16470875.0, 0.0)
[mean_value1] =  (132.21314166666667, 132.33789166666668, 137.25729166666667, 0.0)
[mean_value2] =  (80.26520000000001, 81.59740000000001, 90.3211, 0.0)

mean 자료형:  <class 'numpy.ndarray'> <class 'numpy.float64'>
[mean] =  [132.21314167 132.33789167 137.25729167]
[stddev] =  [73.35044328 68.76754506 63.96477788]

[mean2] =  [80.2652 81.5974 90.3211]
[stddev2] =  [58.91488326 57.57273064 54.0648388 ]


-1

In [13]:
# 5.5.2 행렬 원소 정렬
import numpy as np
import cv2

m = np.random.randint(0, 100, 15).reshape(3,5) # 난수 생성

sort1 = cv2.sort(m, cv2.SORT_EVERY_ROW) # 행(가로 방향)단위 오름차순
sort2 = cv2.sort(m, cv2.SORT_EVERY_COLUMN) # 열(세로 방향)단위 오름차순
sort3 = cv2.sort(m, cv2.SORT_EVERY_ROW+cv2.SORT_DESCENDING) # 행단위 내림차순
sort4 = np.sort(m, axis=1) # x축 정렬
sort5 = np.sort(m, axis=0) # y축 정렬
sort6 = np.sort(m, axis=1)[:, : :-1] # 행 단위 내림차순 정렬

titles = ['m', 'sort1', 'sort2', 'sort3', 'sort4', 'sort5', 'sort6']
for title in titles:
    print("[%s] = \n%s\n" %(title, eval(title)))

[m] = 
[[96 58 51 68 13]
 [ 4 71  3 86 74]
 [30 71 71 43 51]]

[sort1] = 
[[13 51 58 68 96]
 [ 3  4 71 74 86]
 [30 43 51 71 71]]

[sort2] = 
[[ 4 58  3 43 13]
 [30 71 51 68 51]
 [96 71 71 86 74]]

[sort3] = 
[[96 68 58 51 13]
 [86 74 71  4  3]
 [71 71 51 43 30]]

[sort4] = 
[[13 51 58 68 96]
 [ 3  4 71 74 86]
 [30 43 51 71 71]]

[sort5] = 
[[ 4 58  3 43 13]
 [30 71 51 68 51]
 [96 71 71 86 74]]

[sort6] = 
[[96 68 58 51 13]
 [86 74 71  4  3]
 [71 71 51 43 30]]



In [14]:
# 5.5.3 정렬 인덱스 반환
import numpy as np
import cv2

m = np.random.randint(0, 100, 15).reshape(3,5) # 난수 생성

m_sort1 = cv2.sortIdx(m, cv2.SORT_EVERY_ROW) # 정렬 후 원본 인덱스를 반환 (가로 정렬)
m_sort2 = cv2.sortIdx(m, cv2.SORT_EVERY_COLUMN) # 정렬 후 원본 인덱스 반환 (세로 정렬)
m_sort3 = np.argsort(m, axis=0) # 세로 정렬

titles = ['m', 'm_sort1', 'm_sort2', 'm_sort3']
for title in titles:
    print("[%s] = \n%s\n" %(title, eval(title)))


[m] = 
[[ 0 37 52 21 68]
 [80  0 75 95 55]
 [14 15 87 30 30]]

[m_sort1] = 
[[0 3 1 2 4]
 [1 4 2 0 3]
 [0 1 3 4 2]]

[m_sort2] = 
[[0 1 0 0 2]
 [2 2 1 2 1]
 [1 0 2 1 0]]

[m_sort3] = 
[[0 1 0 0 2]
 [2 2 1 2 1]
 [1 0 2 1 0]]



In [16]:
# 5.5.4 사각형 크기로 정렬
import numpy as np
import cv2

# 사각형 정보 출력 함수
def print_rects(rects):
    print("-" * 46)
    print("사각형 원소\t랜덤 사각형 정보\t크기")
    print('-'*46)
    for i, (x,y,w,h,a) in enumerate(rects):
        print("rects[%i] = [(%3d,%3d) from (%3d,%3d)] %5d" %(i,x,y,w,h,a))
    
rands = np.zeros((5, 5), np.uint16) # 5x5 행렬 생성
starts = cv2.randn(rands[:, :2], 100, 50) # 시작 좌표(0, 1열) 랜덤 생성 (평균 100, 표준편차 50) 
ends = cv2.randn(rands[:, 2:-1], 300, 50) # 종료 좌표(2, 3열) 랜덤 생성 (평균 300, 표준편차 50)

sizes = cv2.absdiff(starts, ends) # 차분 절대값 = 크기 = (너비, 높이)
print(sizes)
areas = sizes[:, 0] * sizes[:, 1] # 가로x세로 = 넓이
print(areas)

rects = rands.copy() # 결과 복사
rects[:, 2:-1] = sizes # 2, 3열에 너비와 높이 복사 
rects[:, -1] = areas # 마지막 열에 넓이 저장

idx = cv2.sortIdx(areas, cv2.SORT_EVERY_COLUMN).flatten()

print_rects(rects) # 원본 사각형 정보 출력
print_rects(rects[idx.astype('int')]) # 크기순 정렬 사각형 출력


[[215 257]
 [365 245]
 [225 257]
 [134 146]
 [205 208]]
[55255 23889 57825 19564 42640]
----------------------------------------------
사각형 원소	랜덤 사각형 정보	크기
----------------------------------------------
rects[0] = [(177, 61) from (215,257)] 55255
rects[1] = [(  0, 23) from (365,245)] 23889
rects[2] = [( 32, 97) from (225,257)] 57825
rects[3] = [(168,140) from (134,146)] 19564
rects[4] = [( 87, 74) from (205,208)] 42640
----------------------------------------------
사각형 원소	랜덤 사각형 정보	크기
----------------------------------------------
rects[0] = [(168,140) from (134,146)] 19564
rects[1] = [(  0, 23) from (365,245)] 23889
rects[2] = [( 87, 74) from (205,208)] 42640
rects[3] = [(177, 61) from (215,257)] 55255
rects[4] = [( 32, 97) from (225,257)] 57825


In [17]:
# 5.5.5 행렬 축소 연산
import numpy as np
import cv2

m = np.random.rand(3,5) * 1000//10 # 난수 생성

# reduce() : 차원 축소 함수
reduce_sum = cv2.reduce(m, dim=0, rtype=cv2.REDUCE_SUM) # dim=0 : 열방향(세로) 축소 (= 요소 5개)
reduce_avg = cv2.reduce(m, dim=1, rtype=cv2.REDUCE_AVG) # dim=1 : 행방향(가로) 축소 (= 요소 3개)
reduce_max = cv2.reduce(m, dim=0, rtype=cv2.REDUCE_MAX)
reduce_min = cv2.reduce(m, dim=1, rtype=cv2.REDUCE_MIN) 

print("[m1] = \n%s\n " % m1)
print("[m_reduce_sum] = ", reduce_sum.flatten())
print("[m_reduce_avg] = ", reduce_avg.flatten())
print("[m_reduce_max] = ", reduce_max.flatten())
print("[m_reduce_min] = ", reduce_min.flatten())

[m1] = 
[[ 10 200   5   7   9]
 [ 15  35  60  80 170]
 [100   2  55  37  70]]
 
[m_reduce_sum] =  [ 35. 128. 212. 162. 142.]
[m_reduce_avg] =  [61.8 39.6 34.4]
[m_reduce_max] =  [22. 50. 95. 79. 88.]
[m_reduce_min] =  [4. 9. 6.]


### 5.6 행렬 연산 함수

In [18]:
# 5.6.1 내적 연산
import numpy as np
import cv2

src1 = np.array([1,2,3,1,2,3], np.float32).reshape(2,3)
src2 = np.array([1,2,3,4,5,6], np.float32).reshape(2,3)
src3 = np.array([1,2,1,2,1,2], np.float32).reshape(3,2)
alpha, beta= 1, 1

dst1 = cv2.gemm(src1, src2, alpha, None, beta, flags=cv2.GEMM_1_T) # flags -> 첫 번째 요소(src1)를 전치하여 내적을 구함
dst2 = cv2.gemm(src1, src2, alpha, None, beta, flags=cv2.GEMM_2_T) # flags -> 두 번째 요소(src2)를 전치하여 내적을 구함
dst3 = cv2.gemm(src1, src3, alpha, None, beta)

titles = ['src1', 'src2', 'src3', 'dst1', 'dst2', 'dst3']
for title in titles:
    print("[%s] = \n%s\n" %(title, eval(title)))

[src1] = 
[[1. 2. 3.]
 [1. 2. 3.]]

[src2] = 
[[1. 2. 3.]
 [4. 5. 6.]]

[src3] = 
[[1. 2.]
 [1. 2.]
 [1. 2.]]

[dst1] = 
[[ 5.  7.  9.]
 [10. 14. 18.]
 [15. 21. 27.]]

[dst2] = 
[[14. 32.]
 [14. 32.]]

[dst3] = 
[[ 6. 12.]
 [ 6. 12.]]



In [20]:
# 5.6.2 회전 변환
import numpy as np
import cv2

theta = 20 * np.pi / 180 # 회전할 라디안 각도
rot_mat = np.array([ [np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)] ], np.float32) # 회전 변환 행렬

pts1 = np.array([(250, 30), (400, 70), (350, 250), (150, 200)], np.float32) # 입력 좌표, 사변형을 구성하는 행렬
pts2 = cv2.gemm(pts1, rot_mat, 1, None, 1, flags=cv2.GEMM_2_T) # 행렬곱으로 회전변환

for i, (pt1, pt2) in enumerate(zip(pts1, pts2)):
    print("pts1[%d] = %s, pts2[%d] = %s" %(i, pt1, i, pt2))

image = np.full((400, 500, 3), 255, np.uint8)
cv2.polylines(image, [np.int32(pts1)], True, (0, 255, 0), 2) # 좌표들을 잇는 사변형을 그림
cv2.polylines(image, [np.int32(pts2)], True, (255, 0, 0), 3)
cv2.imshow('image', image)
cv2.waitKey(0)

# 원점을 기준으로 회전하기 때문에 위치가 돌아감
# 도형을 중심으로 회전하고 싶은 경우 도형의 중심을 원점으로 보낸 후 회전하여 다시 원래 위치로 이동하면 됨

pts1[0] = [250.  30.], pts2[0] = [224.66255  113.695816]
pts1[1] = [400.  70.], pts2[1] = [351.93564 202.58655]
pts1[2] = [350. 250.], pts2[2] = [243.38737 354.63022]
pts1[3] = [150. 200.], pts2[3] = [ 72.54986 239.24155]


-1

In [ ]:
# 심화) 물체 자체회전
import numpy as np
import cv2

theta = 20 * np.pi / 180 # 회전할 라디안 각도
rot_mat = np.array([ [np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)] ], np.float32) # 회전 변환 행렬

# 중점 찾기

# 중점을 원점으로 보내기

pts1 = np.array([(250, 30), (400, 70), (350, 250), (150, 200)], np.float32) # 입력 좌표, 사변형을 구성하는 행렬
pts2 = cv2.gemm(pts1, rot_mat, 1, None, 1, flags=cv2.GEMM_2_T) # 행렬곱으로 회전변환

# 원점으로 보낸 중점을 원래 자리로 되돌리기 

for i, (pt1, pt2) in enumerate(zip(pts1, pts2)):
    print("pts1[%d] = %s, pts2[%d] = %s" %(i, pt1, i, pt2))

image = np.full((400, 500, 3), 255, np.uint8)
cv2.polylines(image, [np.int32(pts1)], True, (0, 255, 0), 2) # 좌표들을 잇는 사변형을 그림
cv2.polylines(image, [np.int32(pts2)], True, (255, 0, 0), 3)
cv2.imshow('image', image)
cv2.waitKey(0)


In [1]:
# 5.6.3 연립방정식 풀이
import numpy as np
import cv2

data = [3,0,6,-3,4,2,-5,-1,9] # 연립방정식의 계수
m1 = np.array(data, np.float32).reshape(3,3) # 계수들을 행렬로 생성
m2 = np.array([36,10,28], np.float32) # 상수 벡터

ret, inv = cv2.invert(m1, cv2.DECOMP_LU) # 역행렬 계산
if ret: # 역행렬이 존재하는 경우
    dst1 = inv.dot(m2) # 내적함수 dot 사용 
    dst2 = cv2.gemm(inv, m2, 1, None, 1) # gemm()함수로 내적 계산
    _, dst3 = cv2.solve(m1, m2, cv2.DECOMP_LU) # solve로 연립방정식 해 계산

    print("[inv] = \n%s\n" % inv)
    print("[dst1] = ", dst1.flatten())
    print("[dst2] = ", dst2.flatten())
    print("[dst3] = ", dst3.flatten())
else:
    print("역행렬이 존재하지 않습니다.")

[inv] = 
[[ 0.15079366 -0.02380952 -0.0952381 ]
 [ 0.06746032  0.22619048 -0.0952381 ]
 [ 0.09126984  0.01190476  0.04761905]]

[dst1] =  [2.5238097 2.0238097 4.7380953]
[dst2] =  [2.5238097 2.0238097 4.7380953]
[dst3] =  [2.5238094 2.0238094 4.7380953]
