### 4.4 영상파일 처리 

##### 4.4.1 영상 -> 행렬

In [1]:
# 4.4.1 명암 영상파일 읽기
import cv2

# 행렬의 정보를 출력하는 함수
def print_matInfo(name, image):
    if image.dtype == 'uint8': mat_type = 'CV_8U'
    elif image.dtype == 'int8': mat_type = 'CV_8S'
    elif image.dtype == 'uint16': mat_type = 'CV_16U'
    elif image.dtype == 'int16': mat_type = 'CV_16S'
    elif image.dtype == 'float32': mat_type = 'CV_32F'
    elif image.dtype == 'float64': mat_type = 'CV_64F'
    nchannel = 3 if image.ndim == 3 else 1

    print("%12s: depth(%s), channels(%s) -> mat_type(%sC%d)" %(name, image.dtype, nchannel, mat_type, nchannel))


title1, title2 = 'gray2gray', 'gray2color'
# cv2.imread(파일명, 컬러타입) # 영상을 읽어와 행렬로 변환
gray2gray = cv2.imread("images_04/read_gray.jpg", cv2.IMREAD_GRAYSCALE) # 명암도
gray2color = cv2.imread("images_04/read_gray.jpg", cv2.IMREAD_COLOR) # 컬러 영상

if gray2gray is None or gray2color is None:
    raise Exception("영상파일 읽기 에러")

print("행렬 좌표 (100, 100) 화소값")
print("%s %s" % (title1, gray2gray[100, 100])) # 특정 행렬의 값 출력 (gray라서 하나만 출력됨)
print("%s %s" % (title2, gray2color[100, 100])) # 특정 행렬의 값 출력 (grb 값이 출력됨)

print_matInfo(title1, gray2gray)
print_matInfo(title2, gray2color)

cv2.imshow(title1, gray2gray)
cv2.imshow(title2, gray2color)
cv2.waitKey(0)






행렬 좌표 (100, 100) 화소값
gray2gray 106
gray2color [106 106 106]
   gray2gray: depth(uint8), channels(1) -> mat_type(CV_8UC1)
  gray2color: depth(uint8), channels(3) -> mat_type(CV_8UC3)


-1

위 결과의 2color는 gray를 3채널로 만들었기 때문에 grb 모든 채널이 동일한 값을 가짐

-> 2gray(명암도) 사진과 동일한 결과를 얻음

In [3]:
# 4.4.2 컬러 영상파일 읽기
import cv2

# 행렬의 정보를 출력하는 함수
def print_matInfo(name, image):
    if image.dtype == 'uint8': mat_type = 'CV_8U'
    elif image.dtype == 'int8': mat_type = 'CV_8S'
    elif image.dtype == 'uint16': mat_type = 'CV_16U'
    elif image.dtype == 'int16': mat_type = 'CV_16S'
    elif image.dtype == 'float32': mat_type = 'CV_32F'
    elif image.dtype == 'float64': mat_type = 'CV_64F'
    nchannel = 3 if image.ndim == 3 else 1

    print("%12s: depth(%s), channels(%s) -> mat_type(%sC%d)" %(name, image.dtype, nchannel, mat_type, nchannel))

title1, title2 = 'color2gray', 'color2color'
color2gray = cv2.imread("images_04/read_color.jpg", cv2.IMREAD_GRAYSCALE) # 컬러 영상을 gray로 변경
color2color = cv2.imread("images_04/read_color.jpg", cv2.IMREAD_COLOR) # 컬러

if color2gray is None or color2color is None:
    raise Exception("영상파일 읽기 에러")

print("행렬 좌표 (100, 100) 화소값")
print("%s %s" % (title1, color2gray[100, 100]))
print("%s %s" % (title2, color2color[100, 100]))

print_matInfo(title1, color2gray)
print_matInfo(title2, color2color)

cv2.imshow(title1, color2gray)
cv2.imshow(title2, color2color)
cv2.waitKey(0)





행렬 좌표 (100, 100) 화소값
color2gray 137
color2color [197 145  98]
  color2gray: depth(uint8), channels(1) -> mat_type(CV_8UC1)
 color2color: depth(uint8), channels(3) -> mat_type(CV_8UC3)


-1

In [4]:
# 4.4.3 비트별(16, 32) 영상파일 읽기
import cv2

# 행렬의 정보를 출력하는 함수
def print_matInfo(name, image):
    if image.dtype == 'uint8': mat_type = 'CV_8U'
    elif image.dtype == 'int8': mat_type = 'CV_8S'
    elif image.dtype == 'uint16': mat_type = 'CV_16U'
    elif image.dtype == 'int16': mat_type = 'CV_16S'
    elif image.dtype == 'float32': mat_type = 'CV_32F'
    elif image.dtype == 'float64': mat_type = 'CV_64F'
    nchannel = 3 if image.ndim == 3 else 1

    print("%12s: depth(%s), channels(%s) -> mat_type(%sC%d)" %(name, image.dtype, nchannel, mat_type, nchannel))

title1, title2 = '16bit unchanged', '32bit unchanged'
# cv2.imread("파일이름, 컬러타입")
color2unchanged1 = cv2.imread("images_04/read_16.tif", cv2.IMREAD_UNCHANGED) # 정의된 타입의 영상을 그대로 반환
color2unchanged2 = cv2.imread("images_04/read_32.tif", cv2.IMREAD_UNCHANGED)
if color2unchanged1 is None or color2unchanged2 is None:
    raise Exception("영상파일 읽기 에러")

print_matInfo(title1, color2unchanged1)
print_matInfo(title2, color2unchanged2)

cv2.imshow(title1, color2unchanged1)
cv2.imshow(title2, color2unchanged2)
cv2.waitKey(0)

16bit unchanged: depth(uint16), channels(3) -> mat_type(CV_16UC3)
32bit unchanged: depth(float32), channels(3) -> mat_type(CV_32FC3)


-1

##### 4.4.2 행렬 -> 영상

In [7]:
# 4.4.3 행렬을 영상으로 저장
import cv2
import numpy as np

image = cv2.imread("images_04/read_color.jpg", cv2.IMREAD_COLOR)
if image is None: raise Exception("영상 파일 읽기 에러")

params_jpg = (cv2.IMWRITE_JPEG_QUALITY, 10) # jpeg 화질 설정 (1~100)
params_png = (cv2.IMWRITE_PNG_COMPRESSION, 9) # png 압축 레벨 설정

cv2.imwrite("images_04/result/write_test1.jpg", image) # default 값으로 저장 (95)
cv2.imwrite("images_04/result/write_test2.jpg", image, params_jpg) # 지정한 화질로 저장
cv2.imwrite("images_04/result/write_test3.png", image, params_png)
cv2.imwrite("images_04/result/write_test4.bmp", image)

cv2.imwrite("images_04/result/write_test5.jpg", image, (cv2.IMWRITE_JPEG_QUALITY, 100))
cv2.imwrite("images_04/result/write_test6.jpg", image, (cv2.IMWRITE_JPEG_QUALITY, 70))
cv2.imwrite("images_04/result/write_test7.jpg", image, (cv2.IMWRITE_JPEG_QUALITY, 50))
cv2.imwrite("images_04/result/write_test8.jpg", image, (cv2.IMWRITE_JPEG_QUALITY, 30))

print("완료")



완료


In [11]:
# 4.4.4 8비트 영상 -> 16/32비트 영상
import cv2
import numpy as np

image8 = cv2.imread("images_04/read_color.jpg", cv2.IMREAD_COLOR)
if image8 is None: raise Exception("영상 파일 읽기 에러")
image16 = np.uint16(image8 * (65535/255)) # 형변환, 화소 범위 조정
image32 = np.float32(image8 * (1/255)) # 형변환, 화소 범위 조정

# 화소값 확인 - 관심 영역 출력
print("image8 행렬의 일부\n %s\n" % image8[10:12, 10:13])
print("image16 행렬의 일부\n %s\n" % image16[10:12, 10:13])
print("image32 행렬의 일부\n %s\n" % image32[10:12, 10:13])

# 저장
cv2.imwrite("iamges/write_test_16.tif", image16)
cv2.imwrite("iamges/write_test_32.tif", image32)

cv2.imshow("image16", image16)
cv2.imshow("image32", (image32*255).astype('uint8'))
cv2.waitKey(0)

image8 행렬의 일부
 [[[189 134  91]
  [189 134  91]
  [189 134  91]]

 [[189 134  91]
  [189 134  91]
  [189 134  91]]]

image16 행렬의 일부
 [[[48573 34438 23387]
  [48573 34438 23387]
  [48573 34438 23387]]

 [[48573 34438 23387]
  [48573 34438 23387]
  [48573 34438 23387]]]

image32 행렬의 일부
 [[[0.7411765  0.5254902  0.35686275]
  [0.7411765  0.5254902  0.35686275]
  [0.7411765  0.5254902  0.35686275]]

 [[0.7411765  0.5254902  0.35686275]
  [0.7411765  0.5254902  0.35686275]
  [0.7411765  0.5254902  0.35686275]]]



-1